apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-app

resources:
  - namespace.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - ingress.yaml

images:
  - name: frontend
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/frontend
    newTag: latest
  - name: backend
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/backend
    newTag: latest 