apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - aws-load-balancer-controller.yaml
  - aws-load-balancer-controller-rbac.yaml

vars:
  - name: AWS_ACCOUNT_ID
    objref:
      kind: ConfigMap
      name: aws-auth
      apiVersion: v1
    fieldref:
      fieldpath: data.account_id 