apiVersion: v1
kind: Namespace
metadata:
  name: ack-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-eks-controller
  namespace: ack-system
spec:
  chart:
    spec:
      chart: eks-chart
      sourceRef:
        kind: HelmRepository
        name: ack-eks-repo
        namespace: ack-system
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-ecr-controller
  namespace: ack-system
spec:
  chart:
    spec:
      chart: ecr-chart
      sourceRef:
        kind: HelmRepository
        name: ack-ecr-repo
        namespace: ack-system
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-iam-controller
  namespace: ack-system
spec:
  chart:
    spec:
      chart: iam-chart
      sourceRef:
        kind: HelmRepository
        name: ack-iam-repo
        namespace: ack-system
  interval: 5m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-ec2-controller
  namespace: ack-system
spec:
  chart:
    spec:
      chart: ec2-chart
      sourceRef:
        kind: HelmRepository
        name: ack-ec2-repo
        namespace: ack-system
  interval: 5m 